### ISSUE TITLE
Script to start/ stop Amphetamine Indefinitely on Mac

### ISSUE THREAD

**Issue by alexwolf22** [x74353/AmphetamineBeta#1]
Hello,

I am in the process of customizing my toolbar via [BetterTouchTool](https://community.folivora.ai/t/goldenchaos-btt-the-complete-touch-bar-ui-replacement/1281) and I wanted to make a custom touchbar button to start/ stop amphetamine indefinitely.

Is shell script or code I can run on my mac to do this?

Let me know thanks!

Best,
Alex

**Comment by ajs256** [comment]
Hello,

I am in no way affiliated with the creator of Amphetamine, but I wanted to share something that may help.

The developer's AppleScript documentation is [here](https://iffy.freshdesk.com/support/solutions/articles/48000078223-applescript-documentation). 

I hope this helps!

**Comment by alexwolf22** [comment]
Thanks for sharing this!

The [BetterTouchTool](https://community.folivora.ai/t/goldenchaos-btt-the-complete-touch-bar-ui-replacement/1281) has the ability to write AppleScript for custom buttons so this works perfectly thanks!
