### ISSUE TITLE
This beta has expired

### ISSUE THREAD

**Issue by retpoline** [x74353/AmphetamineBeta#11]
Just installed the AmphetamineBeta app because I wanted to get the Amphetamine without using the appstore, but when I run it I get "This beta has expired... amphetamine will now quit." and it doesn't work.

https://github.com/x74353/AmphetamineBeta/blob/master/Betas/Current/Amphetamine_4%2C3_b4.dmg

How can I use this app? @x74353

Thanks.

**Comment by x74353** [comment]
Hi, if you're still interested in beta testing in 2023, here's where betas are hosted now: testflight.apple.com/join/GeZMOAsG
