### ISSUE TITLE
brew cask install amphetamine

### ISSUE THREAD

**Issue by kingbuzzman** [x74353/AmphetamineBeta#2]
I'm a big `brew` user.. it's a love hate relationship really.. beats `ports`, I digress. I would love to be able to add `amphetamine` to my `setup.sh` where it just goes and instals the thing automagically. Other than using `mas`, that is. What are your thoughts?

**Comment by x74353** [comment]
Hi @kingbuzzman - Sorry for the super delayed reply. Amphetamine is only available on the App Store for now.
