### ISSUE TITLE
[Feature request] Add a session default: until

### ISSUE THREAD

**Issue by ickam** [x74353/AmphetamineBeta#20]
Hi,
First of all, I absolutely love your app and I intend to translate it into Polish at some point.
I just have a small feature request. While setting individual sessions, they can be set until specified time. It would be massively helpful to me if I could set that as a default.
Thank you for your work thus far and for any future improvements!

**Comment by x74353** [comment]
Hi, You can set an until session time from the menu bar
![ScreenShot 2023-03-13 at 19 03 09](https://user-images.githubusercontent.com/1432223/224851573-04ed0f5b-eb5a-46d4-b7b7-65ed5b3794f8.png)

**Comment by x74353** [comment]
You could potentially use a Trigger if you need it to be a repeating schedule.
