### ISSUE TITLE
Cannot open support requests through freshdesk

### ISSUE THREAD

**Issue by ArneTR** [x74353/AmphetamineBeta#4]
Tried multiple e-mail adresses

Tried Safari, Chrome on desktop and Android Device and iPhone. No chance.

Always getting same error:

![Screenshot 2021-01-08 at 15 42 49](https://user-images.githubusercontent.com/250671/104027620-ed821880-51c7-11eb-8faa-611ae6195a21.png)

**Comment by techandrew** [comment]
I'm having this issue too.

**Comment by x74353** [comment]
@ArneTR @techandrew Thanks for reporting this issue. I'm fairly unhappy with Freshdesk's service. Things like this seem to happen often. I've contacted Freshdesk support for assistance as I have not made any recent changes to the support site's settings that would have resulted in this issue.

**Comment by x74353** [comment]
This issue is now resolved.

**Comment by nathanielatom** [comment]
Sorry to re-open/comment on this closed issue, but it says captcha verification failed, after showing a success checkmark and clicking submit. Is repeatable multiple times.

<img width="767" alt="Screen Shot 2021-06-16 at 1 58 17 AM" src="https://user-images.githubusercontent.com/3137319/122165713-99e6bb80-ce46-11eb-93bb-899807670b2e.png">
